<a href="https://colab.research.google.com/github/k-ardliyan/learn-data-science/blob/master/Tugas_Hari_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# List

<h2>Soal 1: Sifat List</h2>

Jawab Pertanyaan di bawah ini:

Jenis data apa saja yang bisa ada di dalam List?

> List dapat diisi dengan tipe data apa saja, string, integer, float, double, boolean, object, dan sebagainya.

In [1]:
def out():
  return print(">>> Output:")

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [2]:
out()
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list
print(a[1:5])

>>> Output:
['13b', 'aa1', 1.32, 22.1]


Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [3]:
out()
a = [1.32, 22.1, 2.34]
b = ['1', '13b', 'aa1']
c = [3, 40, 100]
# combine list
combineList = [a] + [c] + [b]
print(combineList)

>>> Output:
[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]


Expected Output :

[ [1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1'] ]

<h2>Soal 4: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [4]:
out()
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
print(a[1][1:3])

>>> Output:
[0, 6]


Expected Output :


[0, 6]

<h2>Soal 5: Built in Function List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [5]:
out()
p = [0, 5, 2, 10, 4, 9]
# ordered list
print(sorted(p, reverse=False))
# get max value of list
print(max(p))

>>> Output:
[0, 2, 4, 5, 9, 10]
10


Expected Output :

[0, 2, 4, 5, 9, 10]

10

<h2>Soal 6: List Operation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [6]:
out()
a = [1, 3, 5]
b = [5, 1, 3]
# combine list
print(b+a)

>>> Output:
[5, 1, 3, 1, 3, 5]


Expected Output :

[5, 1, 3, 1, 3, 5]

<h2>Soal 7: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [7]:
out()
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value
a[0][2] = 10
# change list value
a[1][0] = 11
print(a)

>>> Output:
[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 8: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [8]:
out()
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del areas[8:10]
print(areas)

>>> Output:
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 9: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [9]:
out()
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T = [evenNumber for evenNumber in S 
     if evenNumber % 2 == 0]

print(T)

>>> Output:
[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]

# Dictionary

<h2>Soal 10: Akses Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [10]:
out()
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
print(europe.keys())
# print nilai dari key france
print(europe['france'])

>>> Output:
dict_keys(['spain', 'france', 'germany', 'norway'])
paris


Expected Output:

dict_keys(['spain', 'france', 'germany', 'norway'])

paris

<h2>Soal 11: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [11]:
out()
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key italy ke objek dictionary dengan value roma
europe['italy'] = 'roma'

# cek apakah itali ada di dalam objek dictionary
print('italy' in europe)

>>> Output:
True


Expected Output:
    
True

<h2>Soal 12: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [12]:
out()
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota germany ke berlin
europe.update({'germany':'berlin'})

# remove australia dari europa
europe.pop('australia')

print(europe)

>>> Output:
{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 13: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [13]:
out()
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota germany?
print(country['germany']['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country.update({'indonesia': {'capital':'jakarta', 'population':250}})

print(country)

>>> Output:
80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 14: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [14]:
out()
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for key, value in country.items():
    print('Ibukota '+ key +' adalah '+ value['capital'])

>>> Output:
Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta

# Tambahan Tugas Hari 4


<h2>Soal 15: Remove Duplicate List</h2>
Buatlah sebuah fungsi, yang menerima suatu argument objek list, dan return sebuah objek list baru, dimana objek list baru ini berisi list sebelumnya dikurangi dengan data yang duplikat, sehingga setiap element di dalam list adalah unik.

Berikan 2 solusi, solusi pertama menggunakan loop dan list, solusi yang kedua menggunakan objek set!

In [15]:
out()
# solusi tanpa menggunakan set
def remove_duplicate(obj_list):
    new_list = []
    for i in obj_list:
      if i not in new_list:
        new_list.append(i)
    return new_list

# solusi dengan menggunakan set
def remove_duplicate_with_set(obj_list):
    new_list = set(obj_list)
    return new_list

obj_list = [1, 2, 4, 6, 2, 1, 4, 5, 7, 8, 6]
print(remove_duplicate(obj_list))
print(remove_duplicate_with_set(obj_list))

>>> Output:
[1, 2, 4, 6, 5, 7, 8]
{1, 2, 4, 5, 6, 7, 8}


output : <br>
[1, 2, 4, 6, 5, 7, 8]<br>
{1, 2, 4, 5, 6, 7, 8}

<h2>Soal 16: Membuat ChatBot Sederhana</h2>
Buatlah sebuah fungsi chatbot yang memberikan suatu respon dimana chatbot ini menerima satu argument string.

Jika argument adalah pertanyaan kemudian chatbot mengecek lagi apakah pertanyaan tersebut adalah pertanyaan yang bisa di jawab atau tidak. Jika pertanyaannya bisa di jawab maka fungsi akan memberikan jawaban yang bersifat random berdasarkan opsi list jawaban yang disediakan berdasarkan jenis pertanyaan tersebut. Jika tidak maka chatbot akan memberikan jawaban default bahwa chatbot tidak mengerti pertanyaannya.

Jika argument adalah bukan pertanyaan maka chatbot akan memberikan sebuah statement random yang disediakan.

In [16]:
out()
# import library
from datetime import datetime
import random

# ganti dengan sebuah nama
nama  = "Kholifatul Ardliyan"
# variabel tanggal
tanggal = datetime.now().day
# default variabel untuk pertanyaan tidak diketahui
default = "maaf, aku tidak tahu jawaban dari pertanyaanmu"

# Membuat objek dictionary berisi berbagai opsi jawaban

# list jawaban untuk pertanyaan tentang nama
jawaban_nama = [
      "nama saya {0}".format(nama),
      "orang-orang memanggil saya {0}".format(nama),
      "panggil saja saya {0}".format(nama)
   ]

# list jawaban untuk pertanyaan tentang tanggal
jawaban_tanggal = [
      "hari ini tanggal {0}".format(tanggal),
      "ya ampun masa tidak tahu, hari ini tanggal {0}".format(tanggal)
    ]

# opsi pertanyaan yang bisa dijawab
pertanyaan = {
  "nama kamu siapa?": jawaban_nama,
  "kamu siapa?" : jawaban_nama,
  "tanggal berapa hari ini?": jawaban_tanggal,
  "hari ini tanggal berapa?" : jawaban_tanggal,
  "default": default
}

# list jawaban untuk sebuah argument selain pertanyaan
statement =  [
                  'ceritakan lebih banyak!',
                  'kenapa kamu berpikir begitu?',
                  'sudah berapa lama kamu merasa seperti ini?',
                  'Itu sangat menarik!',
                  'oh wow!',
                  ':)'
              ]

# respon keseluruhan
responses = {
    'pertanyaan' : pertanyaan,
    'statement' : statement
}
#------
             
# ayo buat chatbotmu
def chatbot(message):
    if "?" in message:
      for value in responses.values():
        if message in value:
            return random.choice(value[message])
        else:
            return value['default']
    else:
        return random.choice(responses['statement'])

print(chatbot('Selamat Pagi'))
print(chatbot('Mau bermain bersamaku?'))
print(chatbot('nama kamu siapa?'))
print(chatbot('hari ini tanggal berapa?'))

>>> Output:
kenapa kamu berpikir begitu?
maaf, aku tidak tahu jawaban dari pertanyaanmu
orang-orang memanggil saya Kholifatul Ardliyan
ya ampun masa tidak tahu, hari ini tanggal 27


output :<br>
:)<br>
maaf, aku tidak tahu jawaban dari pertanyaanmu<br>
orang-orang memanggil saya Nama Anda<br>
ya ampun masa tidak tahu, hari ini tanggal